[project]
name = "testagon"
version = "0.1.0"
description = "Automated invariant detection and test case generation with LLMs"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openai",
    "python-dotenv"
]
